# Generated by Django 3.2.5 on 2021-07-30 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# accounts.migrations.0002_auto_20210724_1959
def migrate_owners(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    AccountUser = apps.get_model("accounts", "AccountUser")

    account_users = [AccountUser(account=account, owner=account.owner) for account in Account.objects.all()]
    AccountUser.objects.bulk_create(account_users)

def reverse_migrate_owners(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    AccountUser = apps.get_model("accounts", "AccountUser")

    for account in Account.objects.all():
        account_user = AccountUser.objects.filter(account_id=account.pk).first()

        if account_user:
            account.owner = account_user.owner
            account.save()

class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_auto_20210724_1959')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            code=migrate_owners,
            reverse_code=reverse_migrate_owners,
            atomic=True,
        ),
        migrations.RemoveField(
            model_name='account',
            name='owner',
        ),
    ]
